includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/resnet12.yaml


device_ids: 0
way_num: 5
shot_num: 1
query_num: 15
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 15
episode_size: 1
train_episode: 100
test_episode: 600

epoch: 200


# batch_size: 32
# pretrain_path: ./results/SKDModel-miniImageNet--ravi-resnet12-5-1-Nov-13-2021-20-30-13/checkpoints/model_best.pth
pretrain_path: ./results/after_Res12.pth

augment_times: 1

save_part:
  - emb_func

log_interval: 20
save_interval: 40

parallel_part:
  - emb_func
  - cls_classifier
  - rot_classifier

classifier:
  name: ProtoNet
  kwargs:
    feat_dim: 640
    num_class: 64
    gamma: 1.0
    alpha: 2.0
    is_distill: False
    # emb_func_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/emb_func_best.pth
    # cls_classifier_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/cls_classifier_best.pth

backbone:
  name: resnet12
  kwargs:
    keep_prob: 0.9

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.0002
    weight_decay: 0.0005
    momentum: 0.9
  other:
    ca: 0.0002
#lr:0.05, ca:0.01

# lr_scheduler info
lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [40]


