includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/SKD.yaml
  - backbones/resnet18.yaml


device_ids: 3
way_num: 5
shot_num: 1
query_num: 15
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 15
episode_size: 1
train_episode: 1000
test_episode: 1000
epoch: 70
image_size: 224

batch_size: 32

augment_times: 1

save_part:
  - emb_func

log_interval: 100
save_interval: 15

parallel_part:
  - emb_func
  - cls_classifier
  - rot_classifier

classifier:
  name: SKDModel
  kwargs:
    feat_dim: 640
    num_class: 100
    gamma: 1.0
    alpha: 2.0
    is_distill: False
    # emb_func_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/emb_func_best.pth
    # cls_classifier_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/cls_classifier_best.pth

# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.9

backbone:
  name: resnet18
  kwargs:
    is_feature: False
    avg_pool: True
    is_flatten: True

# optimizer info
optimizer:
  name: SGD
  kwargs:
    lr: 0.05
    weight_decay: 0.0005
    momentum: 0.9
  other:
    # sa: 0.01
    ca: 0.01
#lr:0.05, ca:0.01

# lr_scheduler info
lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [60]

